image: node:8-stretch

stages:
  - build
  - test
  - scan
  - deploy
  
install:
  stage: build
  script:
    - cd ITAC-Core
    - npm install --only=production
  tags:
    - build
  cache:
    paths:
      - ITAC-Core/node-modules
    policy: push

install_preview:
  stage: build
  before_script:
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
  script:
    - git merge origin/develop --no-commit --no-ff
    - cd ITAC-Core
    - npm install --only=production
  except:
    - master
    - develop
  tags:
    - build

test:
  stage: test
  script:
    - cd ITAC-Core
    - npm install
    - npm test -- --reporter mocha-sonarqube-reporter --reporter-options output=./test-reports/unit.xml
  tags:
    - build
  cache:
    paths:
      - ITAC-Core/node-modules
    policy: pull-push
  artifacts:
    paths:
      - ITAC-Core/test-reports
      - ITAC-Core/coverage
  coverage: '/^Statements\s*:\s*([^%]+)/'


test_preview:
  stage: test
  before_script:
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
  script:
    - git merge origin/develop --no-commit --no-ff
    - cd ITAC-Core
    - npm install
    - npm test -- --reporter mocha-sonarqube-reporter --reporter-options output=./test-reports/unit.xml
  except:
    - master
    - develop
  tags:
    - build
  cache:
    paths:
      - ITAC-Core/node-modules
    policy: pull
  artifacts:
    paths:
      - ITAC-Core/test-reports
      - ITAC-Core/coverage

test_sonar:
  stage: scan
  before_script:
    - apt-get update -y
    - apt-get install -y openjdk-8-jre-headless ca-certificates-java
  script:
    - cd ITAC-Core
    - npm install
    - npm run sonar-scanner -- -Dsonar.host.url=$SONAR_URL -Dsonar.projectKey=$CI_PROJECT_NAME.$CI_COMMIT_REF_SLUG -Dsonar.login=$SONAR_TOKEN -Dsonar.projectVersion=$CI_COMMIT_SHA  -Dsonar.gitlab.url=$GITLAB_URL -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.user_token=$SONAR_PLUGIN_TOKEN -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
  only:
    - master
    - develop
  tags:
    - build
  cache:
    paths:
      - ITAC-Core/node-modules
    policy: pull
  dependencies:
    - test

test_sonar_preview:
  stage: scan
  before_script:
    - apt-get update -y
    - apt-get install -y openjdk-8-jre-headless ca-certificates-java
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
  script:
    - git merge origin/develop --no-commit --no-ff
    - cd ITAC-Core
    - npm install
    - npm run sonar-scanner -- -Dsonar.host.url=$SONAR_URL -Dsonar.projectKey=$CI_PROJECT_NAME.develop -Dsonar.login=$SONAR_TOKEN -Dsonar.projectVersion=$CI_COMMIT_SHA -Dsonar.gitlab.url=$GITLAB_URL -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.user_token=$SONAR_PLUGIN_TOKEN -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.analysis.mode=preview
  except:
    - master
    - develop
  tags:
    - build
  cache:
    paths:
      - ITAC-Core/node-modules
    policy: pull
  dependencies:
    - test_preview

build:image:
  variables:
    IMAGE_TAG1: $CI_REGISTRY_IMAGE/linux:$CI_COMMIT_REF_SLUG
    IMAGE_TAG2: $CI_REGISTRY_IMAGE/linux:$CI_COMMIT_SHA
  stage: deploy
  image: docker
  tags:
    - build-docker-image
    - dind1
  script:
    - docker build -t $IMAGE_TAG1 -t $IMAGE_TAG2  -f Dockerfile.linux .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG1
    - docker push $IMAGE_TAG2
  only:
    - master
    - develop
  when: manual
  environment:
     name: staging