FROM node:8-stretch
WORKDIR /usr/src/app
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY ITAC-Core/package.json ./
RUN npm install --only=production && npm cache clean --force
COPY ITAC-Core/ ./
EXPOSE 3000 8080-8085

CMD [ "npm", "start" ]
