FROM stefanscherer/node-windows:8
RUN mkdir \app
WORKDIR /app
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY ITAC-Core/package.json /app
RUN npm install && npm cache clean --force
COPY ITAC-Core/ /app/
EXPOSE 3000 8080-8085

CMD [ "npm.cmd", "start" ]