FROM stefanscherer/node-windows:8
WORKDIR /usr/src/app
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY ITAC-Core/package.json ./
RUN npm install --only=production && npm cache clean --force
COPY ITAC-Core/ ./
VOLUME  "c:\usr\src\app\session"
EXPOSE 9000 8080-8085

CMD [ "npm.cmd", "start" ]
