FROM node:8
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY ITAC-Core/package.json /usr/src/app
RUN npm install && npm cache clean --force
COPY ITAC-Core/ /usr/src/app/
EXPOSE 3000 8080-8085

CMD [ "npm", "start" ]